export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  MEMBER: 'MEMBER',
  GUEST: 'GUEST',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  // Members
  MEMBERS_READ: 'members:read',
  MEMBERS_APPROVE: 'members:approve',
  MEMBERS_SUSPEND: 'members:suspend',
  MEMBERS_EXPORT: 'members:export',

  // Events
  EVENTS_READ: 'events:read',
  EVENTS_CREATE: 'events:create',
  EVENTS_UPDATE: 'events:update',
  EVENTS_DELETE: 'events:delete',
  EVENTS_RSVP: 'events:rsvp',

  // Content & CMS
  CONTENT_READ: 'content:read',
  CONTENT_CREATE: 'content:create',
  CONTENT_UPDATE: 'content:update',
  CONTENT_PUBLISH: 'content:publish',
  CONTENT_DELETE: 'content:delete',

  // Resources
  RESOURCES_READ: 'resources:read',
  RESOURCES_CREATE: 'resources:create',
  RESOURCES_DELETE: 'resources:delete',

  // Payments & Finance
  PAYMENTS_READ: 'payments:read',
  PAYMENTS_CREATE: 'payments:create',
  PAYMENTS_REFUND: 'payments:refund',
  PAYMENTS_EXPORT: 'payments:export',

  // Theme & Settings
  THEME_READ: 'theme:read',
  THEME_UPDATE: 'theme:update',
  THEME_PUBLISH: 'theme:publish',

  // Audit & Roles
  AUDIT_READ: 'audit:read',
  ROLES_MANAGE: 'roles:manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.MEMBERS_APPROVE,
    PERMISSIONS.MEMBERS_SUSPEND,
    PERMISSIONS.MEMBERS_EXPORT,
    PERMISSIONS.EVENTS_READ,
    PERMISSIONS.EVENTS_CREATE,
    PERMISSIONS.EVENTS_UPDATE,
    PERMISSIONS.EVENTS_RSVP,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.CONTENT_PUBLISH,
    PERMISSIONS.RESOURCES_READ,
    PERMISSIONS.RESOURCES_CREATE,
    PERMISSIONS.RESOURCES_DELETE,
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.PAYMENTS_REFUND,
    PERMISSIONS.PAYMENTS_EXPORT,
    PERMISSIONS.THEME_READ,
    PERMISSIONS.THEME_UPDATE,
    PERMISSIONS.THEME_PUBLISH,
    PERMISSIONS.AUDIT_READ,
  ],
  MODERATOR: [
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.EVENTS_READ,
    PERMISSIONS.EVENTS_UPDATE,
    PERMISSIONS.EVENTS_RSVP,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.RESOURCES_READ,
    PERMISSIONS.RESOURCES_CREATE,
  ],
  MEMBER: [
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.EVENTS_READ,
    PERMISSIONS.EVENTS_RSVP,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.RESOURCES_READ,
    PERMISSIONS.PAYMENTS_CREATE,
  ],
  GUEST: [
    PERMISSIONS.EVENTS_READ,
    PERMISSIONS.EVENTS_RSVP,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.PAYMENTS_CREATE,
  ],
};

export const SENSITIVE_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.PAYMENTS_REFUND,
  PERMISSIONS.THEME_PUBLISH,
  PERMISSIONS.ROLES_MANAGE,
  PERMISSIONS.MEMBERS_SUSPEND,
];
